concurrency: test-${{ github.ref }}

name: Container image test

on:
  schedule:
    - cron: '*/4 * * * *'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      goreportcard:
        image: sierra1011/goreportcard:latest 
        ports:
          - 80:8000
    steps:
      - name: Check curl response
        run: curl http://goreportcard:80