concurrency: test-${{ github.ref }}

name: Container image test

on:
  schedule:
    - cron: '*/4 * * * *'  # 2 minutes
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sierra1011/goreportcard:latest 
      ports:
        - 8000
    steps:
      - name: Check curl response
        run: curl localhost:8000